const size = {
  mobileS: '320px',
  mobileM: '375px',
  mobileL: '425px',
  mobileXL: '500px',
  mobileXXL: '700px',
  tablet: '768px',
  tabletS: '875px',
  laptop: '1024px',
  laptopS: '1165px',
  laptopM: '1270px',
  laptopML: '1340px',
  laptopL: '1440px',
  laptopXL: '1740px',
  desktop: '2560px',
};
export const device = {
  mobileS: `(min-width: ${size.mobileS})`,
  mobileM: `(min-width: ${size.mobileM})`,
  mobileL: `(min-width: ${size.mobileL})`,
  mobileXL: `(min-width: ${size.mobileXL})`,
  mobileXXL: `(min-width: ${size.mobileXXL})`,
  tablet: `(min-width: ${size.tablet})`,
  tabletS: `(min-width: ${size.tabletS})`,
  laptop: `(min-width: ${size.laptop})`,
  laptopS: `(min-width: ${size.laptopS})`,
  laptopM: `(min-width: ${size.laptopM})`,
  laptopML: `(min-width: ${size.laptopML})`,
  laptopL: `(min-width: ${size.laptopL})`,
  laptopXL: `(min-width: ${size.laptopXL})`,
  desktop: `(min-width: ${size.desktop})`,
  desktopL: `(min-width: ${size.desktop})`,
};
